name: "Lint and test"

on: [push, pull_request]

jobs:

  build-and-test:

    strategy:
      matrix:
        node-version: ["14", "16", "18", "19"]

    name: "Lint and test"
    runs-on: ubuntu-latest

    steps:

      - name: "Checkout the repository"
        uses: actions/checkout@v3

      - name: "Set up Node ${{ matrix.node-version }}"
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: "Install dependencies"
        run: |
          npm install

      - name: "Lint"
        run: |
          npx grunt lint

      - name: "Tests"
        run: |
          npx grunt test

